# Generated by Django 5.2.3 on 2025-11-03 01:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('documento', models.CharField(blank=True, max_length=18)),
                ('status', models.CharField(default='ativo', max_length=12)),
                ('pix_chave', models.CharField(blank=True, max_length=120)),
                ('banco_agencia_conta', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_comissao', models.CharField(choices=[('percentual_venda', '% sobre venda'), ('valor_fixopornumero', 'R$ por número'), ('percentual_sobre_lucro', '% sobre lucro')], default='percentual_venda', max_length=40)),
                ('valor_comissao', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cookie_days', models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('atribuicao', models.CharField(default='last_click', max_length=12)),
                ('permitir_compra_propria', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True)),
                ('tipo', models.CharField(choices=[('percentual', '%'), ('valor', 'R$')], default='percentual', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uso_global', models.PositiveIntegerField(blank=True, null=True)),
                ('max_uso_por_cliente', models.PositiveIntegerField(blank=True, null=True)),
                ('min_compra', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('qtd_min_numeros', models.PositiveIntegerField(blank=True, null=True)),
                ('so_primeira_compra', models.BooleanField(default=False)),
                ('acumulavel', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('uso_cache', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('qtd_numeros_min', models.PositiveIntegerField(blank=True, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('percentual', '%'), ('valor', 'R$')], default='percentual', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('prioridade', models.IntegerField(default=0)),
                ('exclusiva', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ativo', '-prioridade', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('event_id', models.CharField(db_index=True, max_length=80)),
                ('raw', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(max_length=32, unique=True)),
                ('url_destino', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='rifas.affiliate')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='rifas.affiliateprogram')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cpf', models.CharField(db_index=True, max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cpf'], name='rifas_clien_cpf_32c485_idx'), models.Index(fields=['email'], name='rifas_clien_email_158a9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AffiliateAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expira_em', models.DateTimeField()),
                ('modelo', models.CharField(default='last_click', max_length=12)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='rifas.affiliatelink')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_attributions', to='rifas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('documento', models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas_logos/')),
                ('whatsapp_suporte', models.URLField(blank=True, help_text='Link do WhatsApp para suporte geral da empresa', null=True)),
                ('whatsapp_grupo', models.URLField(blank=True, help_text='Link do grupo/comunidade da empresa', null=True)),
                ('dominio_publico', models.URLField(blank=True, help_text='Ex.: https://rifas.meucliente.com.br — usado para montar o webhook da Efí', null=True)),
                ('subdominio', models.CharField(blank=True, help_text='Opcional. Ex.: cliente01 (o sistema pode montar cliente01.seudominio.com)', max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxa_admin_percentual_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual padrão da operadora, ex: 3.99', max_digits=5)),
                ('taxa_admin_fixa_padrao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa fixa padrão por ação, ex: 1.00', max_digits=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EfiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome interno')),
                ('client_id', models.CharField(max_length=180)),
                ('client_secret', models.CharField(max_length=180)),
                ('certificate', models.FileField(blank=True, help_text='Arquivo ÚNICO .pem/.p12 da Efí (cert + key no mesmo arquivo).', null=True, upload_to='efi_certs/')),
                ('certificate_cert', models.FileField(blank=True, help_text='CERT do cliente (.pem) — se usar arquivo separado.', null=True, upload_to='efi_certs/')),
                ('certificate_key', models.FileField(blank=True, help_text='KEY do cliente (.key/.pem) — se usar arquivo separado.', null=True, upload_to='efi_certs/')),
                ('chave_pix', models.CharField(help_text='Chave Pix cadastrada na Efí', max_length=140)),
                ('sandbox', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('webhook_url_registrado', models.URLField(blank=True, help_text='Última URL de webhook registrada na Efí para esta credencial.', null=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Se preenchido, essa conta é da empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='efi_configs', to='rifas.empresa')),
            ],
            options={
                'verbose_name': 'Configuração Efí',
                'verbose_name_plural': 'Configurações Efí',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='em_processamento', max_length=20)),
                ('comprovante_url', models.URLField(blank=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='rifas.affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto_regras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('desconto_cupom', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendente', max_length=10)),
                ('pricing_breakdown', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='rifas.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='efi', max_length=30)),
                ('provider_preference_id', models.CharField(blank=True, max_length=80, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=80, null=True)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('copia_cola', models.TextField(blank=True, null=True)),
                ('efi_txid', models.CharField(blank=True, help_text='txid da cobrança Pix gerada na Efí', max_length=64, null=True)),
                ('efi_loc_id', models.CharField(blank=True, help_text='ID do location na Efí (para recuperar QRCode)', max_length=32, null=True)),
                ('status_provider', models.CharField(blank=True, max_length=30, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='rifas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='rifas.discountrule')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_applications', to='rifas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to='rifas.cliente')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rifas.coupon')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='rifas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='pendente', max_length=10)),
                ('motivo_negacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='rifas.affiliate')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='rifas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='rifas_banners/')),
                ('preco_numero', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantidade_numeros', models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1)])),
                ('inicio_vendas', models.DateTimeField()),
                ('fim_vendas', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('permitir_numero_escolhido', models.BooleanField(default=True)),
                ('limite_por_pedido', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('minutos_expiracao_reserva', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('mostrar_top_compradores', models.BooleanField(default=True)),
                ('em_vendas', models.BooleanField(default=True)),
                ('link_whatsapp', models.URLField(blank=True, help_text='Se preencher aqui, usa este link de suporte. Senão, usa o da empresa.', null=True)),
                ('link_grupo', models.URLField(blank=True, help_text='Se preencher aqui, usa este link de grupo. Senão, usa o da empresa.', null=True)),
                ('meio_pagamento', models.CharField(choices=[('efi', 'Efí (Gerencianet)')], default='efi', help_text='Define se esta rifa cobra pela Efí (Pix).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_criadas', to=settings.AUTH_USER_MODEL)),
                ('efi_config', models.ForeignKey(blank=True, help_text='Se definido, esta rifa sempre usará esta credencial Efí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_usando', to='rifas.eficonfig')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa dona/responsável pela rifa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas', to='rifas.empresa')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.CharField(max_length=200)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='rifas.rifa')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='rifa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='rifas.rifa'),
        ),
        migrations.AddField(
            model_name='eficonfig',
            name='rifa',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, essa conta é só desta rifa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='efi_configs', to='rifas.rifa'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='rifas.rifa'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='rifas.rifa'),
        ),
        migrations.CreateModel(
            name='CotaPremiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor_premio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_premiadas', to='rifas.rifa')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='affiliateprogram',
            name='rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_programs', to='rifas.rifa'),
        ),
        migrations.CreateModel(
            name='RifaFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_premio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo do prêmio principal.', max_digits=12)),
                ('premio_top_comprador', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prêmio do top comprador (se tiver).', max_digits=12)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outras despesas da ação.', max_digits=12)),
                ('taxa_admin_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se > 0, usa esta taxa (%) em vez da da empresa.', max_digits=5)),
                ('taxa_admin_fixa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se > 0, usa esta taxa (R$) em vez da da empresa.', max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rifa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='rifas.rifa')),
            ],
            options={
                'verbose_name': 'Financeiro da rifa',
                'verbose_name_plural': 'Financeiros de rifa',
            },
        ),
        migrations.CreateModel(
            name='RifaPremiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('principal', 'Prêmio principal'), ('cota_premiada', 'Cota premiada'), ('top_comprador', 'Top comprador'), ('extra', 'Outro / Manual')], default='principal', max_length=20)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pago', models.BooleanField(default=False)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiacoes', to='rifas.cliente')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes', to='rifas.rifa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizado_em', models.DateTimeField(blank=True, null=True)),
                ('numero_sorteado', models.PositiveIntegerField(blank=True, null=True)),
                ('auditoria_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('rifa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sorteio', to='rifas.rifa')),
            ],
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.TextField(blank=True)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='rifas.affiliatelink')),
            ],
            options={
                'indexes': [models.Index(fields=['clicked_at'], name='rifas_affil_clicked_034f36_idx')],
            },
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('reservado', 'Reservado'), ('pago', 'Pago')], db_index=True, default='livre', max_length=10)),
                ('reservado_em', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros', to='rifas.cliente')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeros', to='rifas.pedido')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='rifas.rifa')),
            ],
            options={
                'indexes': [models.Index(fields=['rifa', 'status'], name='rifas_numer_rifa_id_141cfd_idx'), models.Index(fields=['rifa', 'numero'], name='rifas_numer_rifa_id_a1c6b1_idx')],
                'unique_together': {('rifa', 'numero')},
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['codigo'], name='rifas_coupo_codigo_10eace_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotapremiada',
            unique_together={('rifa', 'numero')},
        ),
    ]
