# Generated by Django 5.2.3 on 2025-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='em_vendas',
            field=models.BooleanField(default=True),
        ),
    ]
