# Generated by Django 5.2.3 on 2025-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficonfig',
            name='webhook_url_registrado',
            field=models.URLField(blank=True, help_text='Última URL de webhook registrada na Efí para esta credencial.', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dominio_publico',
            field=models.URLField(blank=True, help_text='Ex.: https://rifas.meucliente.com.br — usado para montar o webhook da Efí', null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='subdominio',
            field=models.CharField(blank=True, help_text='Opcional. Ex.: cliente01 (o sistema pode montar cliente01.seudominio.com)', max_length=80, null=True),
        ),
    ]
