# Generated by Django 5.2.3 on 2025-10-31 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_rifa_em_vendas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='tem_cotas_premiadas',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CotaPremiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente_ganhador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotas_premiadas_ganhas', to='rifas.cliente')),
                ('numero_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cota_premiada', to='rifas.numero')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotas_premiadas', to='rifas.rifa')),
            ],
            options={
                'ordering': ['rifa', 'numero'],
                'unique_together': {('rifa', 'numero')},
            },
        ),
    ]
