# Generated by Django 5.2.3 on 2025-11-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0002_eficonfig_webhook_url_registrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficonfig',
            name='certificate_cert',
            field=models.FileField(blank=True, help_text='CERT do cliente (.pem) — se usar arquivo separado.', null=True, upload_to='efi_certs/'),
        ),
        migrations.AddField(
            model_name='eficonfig',
            name='certificate_key',
            field=models.FileField(blank=True, help_text='KEY do cliente (.key/.pem) — se usar arquivo separado.', null=True, upload_to='efi_certs/'),
        ),
        migrations.AlterField(
            model_name='eficonfig',
            name='certificate',
            field=models.FileField(blank=True, help_text='Arquivo ÚNICO .pem/.p12 da Efí (cert + key no mesmo arquivo).', null=True, upload_to='efi_certs/'),
        ),
    ]
