# Generated by Django 5.2.3 on 2025-10-31 13:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0003_rifa_tem_cotas_premiadas_cotapremiada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotapremiada',
            options={'ordering': ['numero']},
        ),
        migrations.RenameField(
            model_name='cotapremiada',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='cotapremiada',
            name='cliente_ganhador',
        ),
        migrations.RemoveField(
            model_name='cotapremiada',
            name='numero_instance',
        ),
        migrations.RemoveField(
            model_name='cotapremiada',
            name='pago_em',
        ),
        migrations.RemoveField(
            model_name='rifa',
            name='tem_cotas_premiadas',
        ),
        migrations.AddField(
            model_name='rifa',
            name='link_grupo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='link_whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotapremiada',
            name='valor_premio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
