# Generated by Django 5.2.3 on 2025-11-01 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0005_empresa_rifa_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='efi_loc_id',
            field=models.CharField(blank=True, help_text='ID do location na Efí (para recuperar QRCode)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='efi_txid',
            field=models.CharField(blank=True, help_text='txid da cobrança Pix gerada na Efí', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rifa',
            name='meio_pagamento',
            field=models.CharField(choices=[('mp', 'Mercado Pago'), ('efi', 'Efí (Gerencianet)')], default='mp', help_text='Define se esta rifa cobra pelo Mercado Pago ou pela Efí.', max_length=10),
        ),
        migrations.CreateModel(
            name='EfiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome interno')),
                ('client_id', models.CharField(max_length=180)),
                ('client_secret', models.CharField(max_length=180)),
                ('certificate', models.FileField(blank=True, help_text='Arquivo .pem/.p12 da Efí (se sua conta exigir)', null=True, upload_to='efi_certs/')),
                ('chave_pix', models.CharField(help_text='Chave Pix cadastrada na Efí', max_length=140)),
                ('sandbox', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Se preenchido, essa conta é da empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='efi_configs', to='rifas.empresa')),
                ('rifa', models.ForeignKey(blank=True, help_text='Se preenchido, essa conta é só desta rifa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='efi_configs', to='rifas.rifa')),
            ],
            options={
                'verbose_name': 'Configuração Efí',
                'verbose_name_plural': 'Configurações Efí',
            },
        ),
        migrations.AddField(
            model_name='rifa',
            name='efi_config',
            field=models.ForeignKey(blank=True, help_text='Se definido, esta rifa sempre usará esta credencial Efí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifas_usando', to='rifas.eficonfig'),
        ),
    ]
