# Generated by Django 5.2.3 on 2025-11-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0006_pagamento_efi_loc_id_pagamento_efi_txid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='provider',
            field=models.CharField(default='efi', max_length=30),
        ),
        migrations.AlterField(
            model_name='rifa',
            name='meio_pagamento',
            field=models.CharField(choices=[('efi', 'Efí (Gerencianet)')], default='efi', help_text='Define se esta rifa cobra pela Efí (Pix).', max_length=10),
        ),
    ]
