# Generated by Django 5.2.3 on 2025-11-01 17:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0007_alter_pagamento_provider_alter_rifa_meio_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='taxa_admin_fixa_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa fixa padrão por ação, ex: 1.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='empresa',
            name='taxa_admin_percentual_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentual padrão da operadora, ex: 3.99', max_digits=5),
        ),
        migrations.CreateModel(
            name='RifaFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_premio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo do prêmio principal.', max_digits=12)),
                ('premio_top_comprador', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Prêmio do top comprador (se tiver).', max_digits=12)),
                ('outras_despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outras despesas da ação.', max_digits=12)),
                ('taxa_admin_percentual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se > 0, usa esta taxa (%) em vez da da empresa.', max_digits=5)),
                ('taxa_admin_fixa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Se > 0, usa esta taxa (R$) em vez da da empresa.', max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('rifa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='rifas.rifa')),
            ],
            options={
                'verbose_name': 'Financeiro da rifa',
                'verbose_name_plural': 'Financeiros de rifa',
            },
        ),
    ]
