# Generated by Django 5.2.3 on 2025-11-01 18:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0008_empresa_taxa_admin_fixa_padrao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RifaPremiacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('principal', 'Prêmio principal'), ('cota_premiada', 'Cota premiada'), ('top_comprador', 'Top comprador'), ('extra', 'Outro / Manual')], default='principal', max_length=20)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pago', models.BooleanField(default=False)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premiacoes', to='rifas.cliente')),
                ('rifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiacoes', to='rifas.rifa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
